name: pre-commit

on: [push, pull_request]
concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}
permissions:
  contents: read

env:
  SKIP: clang-format, no-commit-to-branch

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run:  python -m pip install networkx
    - uses: pre-commit/action@v3.0.1
